using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Barcoder.Utils
{
    internal static class Gs1Encoder
    {
        private static readonly Lazy<IReadOnlyDictionary<string, string>> RegularExpressionLookup
            = new Lazy<IReadOnlyDictionary<string, string>>(() => ApplicationIdentifiers.ToDictionary(x => x.Ai, x => x.RegularExpression));

        private static readonly Lazy<IReadOnlyDictionary<string, bool>> Fnc1RequiredLookup
            = new Lazy<IReadOnlyDictionary<string, bool>>(() => ApplicationIdentifiers.ToDictionary(x => x.Ai, x => x.Fnc1Required));

        public static string Encode(string content, char fnc1)
        {
            content = RemoveSpaces(content);
            var encodedString = new StringBuilder();
            encodedString.Append(fnc1);
            foreach (Match elementMatch in Regex.Matches(content, @"\((?<ai>[0-9]+)\)(?<data>[^()]+)"))
            {
                string applicationIdentifier = elementMatch.Groups["ai"].Value;
                string data = elementMatch.Groups["data"].Value;

                if (RegularExpressionLookup.Value.TryGetValue(applicationIdentifier, out string regularExpression)
                    && !Regex.IsMatch(applicationIdentifier + data, regularExpression))
                {
                    throw new ArgumentException($"Application identifier '{applicationIdentifier + data}' does not match '{regularExpression}'", nameof(content));
                }

                if (!Fnc1RequiredLookup.Value.TryGetValue(applicationIdentifier, out bool fnc1Required))
                    fnc1Required = true;

                encodedString.Append(applicationIdentifier);
                encodedString.Append(data);
                if (fnc1Required)
                    encodedString.Append(fnc1);
            }

            return encodedString.ToString().TrimEnd(fnc1);
        }

        private static string RemoveSpaces(string content)
            => content.Replace(" ", string.Empty);

        // Extracted from https://www.gs1.org/standards/barcodes/application-identifiers using some JavaScript:
        //
        // console.log(Array.prototype.map.call(document.querySelectorAll('#DataTables_Table_0 > tbody > tr.datatables-hidden'), tr => {
        //   const ai = tr.querySelector('td[data-label*="AI"]').innerText.trim();
        //   const description = tr.querySelector('td[data-label*="Description"]').innerText.trim();
        //   const format = tr.querySelector('td[data-label*="Format"]').innerText.trim();
        //   const dataTitle = tr.querySelector('td[data-label*="Data title"]').innerText.trim();
        //   const fnc1Required = tr.querySelector('td[data-label*="FNC1"]').innerText.trim() !== 'No';
        //   const regularExpression = tr.querySelector('td[data-label*="Regular expression"]').innerText.trim();
        //   return `new ApplicationIdentifier { Ai = "${ai}", Fnc1Required = ${fnc1Required}, DataTitle = "${dataTitle}", RegularExpression = @"${regularExpression}" },`;
        // }).join('\n'));
        //
        private static readonly ApplicationIdentifier[] ApplicationIdentifiers = new[]
        {
            new ApplicationIdentifier { Ai = "00", Fnc1Required = false, DataTitle = "SSCC", RegularExpression = @"^00(\d{18})$" },
            new ApplicationIdentifier { Ai = "01", Fnc1Required = false, DataTitle = "GTIN", RegularExpression = @"^01(\d{14})$" },
            new ApplicationIdentifier { Ai = "02", Fnc1Required = false, DataTitle = "CONTENT", RegularExpression = @"^02(\d{14})$" },
            new ApplicationIdentifier { Ai = "10", Fnc1Required = true, DataTitle = "BATCH/LOT", RegularExpression = @"^10([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "11", Fnc1Required = false, DataTitle = "PROD DATE", RegularExpression = @"^11(\d{6})$" },
            new ApplicationIdentifier { Ai = "12", Fnc1Required = false, DataTitle = "DUE DATE", RegularExpression = @"^12(\d{6})$" },
            new ApplicationIdentifier { Ai = "13", Fnc1Required = false, DataTitle = "PACK DATE", RegularExpression = @"^13(\d{6})$" },
            new ApplicationIdentifier { Ai = "15", Fnc1Required = false, DataTitle = "BEST BEFORE or BEST BY", RegularExpression = @"^15(\d{6})$" },
            new ApplicationIdentifier { Ai = "16", Fnc1Required = false, DataTitle = "SELL BY", RegularExpression = @"^16(\d{6})$" },
            new ApplicationIdentifier { Ai = "17", Fnc1Required = false, DataTitle = "USE BY OR EXPIRY", RegularExpression = @"^17(\d{6})$" },
            new ApplicationIdentifier { Ai = "20", Fnc1Required = false, DataTitle = "VARIANT", RegularExpression = @"^20(\d{2})$" },
            new ApplicationIdentifier { Ai = "21", Fnc1Required = true, DataTitle = "SERIAL", RegularExpression = @"^21([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "22", Fnc1Required = true, DataTitle = "CPV", RegularExpression = @"^22([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "235", Fnc1Required = false, DataTitle = "TPX", RegularExpression = @"243([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,28})$" },
            new ApplicationIdentifier { Ai = "240", Fnc1Required = true, DataTitle = "ADDITIONAL ID", RegularExpression = @"^240([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "241", Fnc1Required = true, DataTitle = "CUST. PART NO.", RegularExpression = @"^241([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "242", Fnc1Required = true, DataTitle = "MTO VARIANT", RegularExpression = @"^242(\d{0,6})$" },
            new ApplicationIdentifier { Ai = "243", Fnc1Required = true, DataTitle = "PCN", RegularExpression = @"^243([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "250", Fnc1Required = true, DataTitle = "SECONDARY SERIAL", RegularExpression = @"^250([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "251", Fnc1Required = true, DataTitle = "REF. TO SOURCE", RegularExpression = @"^251([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "253", Fnc1Required = true, DataTitle = "GDTI", RegularExpression = @"^253(\d{13})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,17})$" },
            new ApplicationIdentifier { Ai = "254", Fnc1Required = true, DataTitle = "GLN EXTENSION COMPONENT", RegularExpression = @"^254([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "255", Fnc1Required = true, DataTitle = "GCN", RegularExpression = @"^255(\d{13})(\d{0,12})$" },
            new ApplicationIdentifier { Ai = "30", Fnc1Required = true, DataTitle = "VAR. COUNT", RegularExpression = @"^30(\d{0,8})$" },
            new ApplicationIdentifier { Ai = "3101", Fnc1Required = false, DataTitle = "NET WEIGHT (kg)", RegularExpression = @"^3101(\d{6})$" },
            new ApplicationIdentifier { Ai = "3102", Fnc1Required = false, DataTitle = "NET WEIGHT (kg)", RegularExpression = @"^3102(\d{6})$" },
            new ApplicationIdentifier { Ai = "3103", Fnc1Required = false, DataTitle = "NET WEIGHT (kg)", RegularExpression = @"^3103(\d{6})$" },
            new ApplicationIdentifier { Ai = "3104", Fnc1Required = false, DataTitle = "NET WEIGHT (kg)", RegularExpression = @"^3104(\d{6})$" },
            new ApplicationIdentifier { Ai = "3105", Fnc1Required = false, DataTitle = "NET WEIGHT (kg)", RegularExpression = @"^3105(\d{6})$" },
            new ApplicationIdentifier { Ai = "3110", Fnc1Required = false, DataTitle = "LENGTH (m)", RegularExpression = @"^3110(\d{6})$" },
            new ApplicationIdentifier { Ai = "3111", Fnc1Required = false, DataTitle = "LENGTH (m)", RegularExpression = @"^3111(\d{6})$" },
            new ApplicationIdentifier { Ai = "3112", Fnc1Required = false, DataTitle = "LENGTH (m)", RegularExpression = @"^3112(\d{6})$" },
            new ApplicationIdentifier { Ai = "3113", Fnc1Required = false, DataTitle = "LENGTH (m)", RegularExpression = @"^3113(\d{6})$" },
            new ApplicationIdentifier { Ai = "3114", Fnc1Required = false, DataTitle = "LENGTH (m)", RegularExpression = @"^3114(\d{6})$" },
            new ApplicationIdentifier { Ai = "3115", Fnc1Required = false, DataTitle = "LENGTH (m)", RegularExpression = @"^3115(\d{6})$" },
            new ApplicationIdentifier { Ai = "3120", Fnc1Required = false, DataTitle = "WIDTH (m)", RegularExpression = @"^3120(\d{6})$" },
            new ApplicationIdentifier { Ai = "3121", Fnc1Required = false, DataTitle = "WIDTH (m)", RegularExpression = @"^3121(\d{6})$" },
            new ApplicationIdentifier { Ai = "3122", Fnc1Required = false, DataTitle = "WIDTH (m)", RegularExpression = @"^3122(\d{6})$" },
            new ApplicationIdentifier { Ai = "3123", Fnc1Required = false, DataTitle = "WIDTH (m)", RegularExpression = @"^3123(\d{6})$" },
            new ApplicationIdentifier { Ai = "3124", Fnc1Required = false, DataTitle = "WIDTH (m)", RegularExpression = @"^3124(\d{6})$" },
            new ApplicationIdentifier { Ai = "3125", Fnc1Required = false, DataTitle = "WIDTH (m)", RegularExpression = @"^3125(\d{6})$" },
            new ApplicationIdentifier { Ai = "3130", Fnc1Required = false, DataTitle = "HEIGHT (m)", RegularExpression = @"^3130(\d{6})$" },
            new ApplicationIdentifier { Ai = "3131", Fnc1Required = false, DataTitle = "HEIGHT (m)", RegularExpression = @"^3131(\d{6})$" },
            new ApplicationIdentifier { Ai = "3132", Fnc1Required = false, DataTitle = "HEIGHT (m)", RegularExpression = @"^3132(\d{6})$" },
            new ApplicationIdentifier { Ai = "3133", Fnc1Required = false, DataTitle = "HEIGHT (m)", RegularExpression = @"^3133(\d{6})$" },
            new ApplicationIdentifier { Ai = "3134", Fnc1Required = false, DataTitle = "HEIGHT (m)", RegularExpression = @"^3134(\d{6})$" },
            new ApplicationIdentifier { Ai = "3135", Fnc1Required = false, DataTitle = "HEIGHT (m)", RegularExpression = @"^3135(\d{6})$" },
            new ApplicationIdentifier { Ai = "3140", Fnc1Required = false, DataTitle = "AREA (m2)", RegularExpression = @"^3140(\d{6})$" },
            new ApplicationIdentifier { Ai = "3141", Fnc1Required = false, DataTitle = "AREA (m2)", RegularExpression = @"^3141(\d{6})$" },
            new ApplicationIdentifier { Ai = "3142", Fnc1Required = false, DataTitle = "AREA (m2)", RegularExpression = @"^3142(\d{6})$" },
            new ApplicationIdentifier { Ai = "3143", Fnc1Required = false, DataTitle = "AREA (m2)", RegularExpression = @"^3143(\d{6})$" },
            new ApplicationIdentifier { Ai = "3144", Fnc1Required = false, DataTitle = "AREA (m2)", RegularExpression = @"^3144(\d{6})$" },
            new ApplicationIdentifier { Ai = "3145", Fnc1Required = false, DataTitle = "AREA (m2)", RegularExpression = @"^3145(\d{6})$" },
            new ApplicationIdentifier { Ai = "3150", Fnc1Required = false, DataTitle = "NET VOLUME (l)", RegularExpression = @"^3150(\d{6})$" },
            new ApplicationIdentifier { Ai = "3151", Fnc1Required = false, DataTitle = "NET VOLUME (l)", RegularExpression = @"^3151(\d{6})$" },
            new ApplicationIdentifier { Ai = "3152", Fnc1Required = false, DataTitle = "NET VOLUME (l)", RegularExpression = @"^3152(\d{6})$" },
            new ApplicationIdentifier { Ai = "3153", Fnc1Required = false, DataTitle = "NET VOLUME (l)", RegularExpression = @"^3153(\d{6})$" },
            new ApplicationIdentifier { Ai = "3154", Fnc1Required = false, DataTitle = "NET VOLUME (l)", RegularExpression = @"^3154(\d{6})$" },
            new ApplicationIdentifier { Ai = "3155", Fnc1Required = false, DataTitle = "NET VOLUME (l)", RegularExpression = @"^3155(\d{6})$" },
            new ApplicationIdentifier { Ai = "3160", Fnc1Required = false, DataTitle = "NET VOLUME (m3)", RegularExpression = @"^3160(\d{6})$" },
            new ApplicationIdentifier { Ai = "3161", Fnc1Required = false, DataTitle = "NET VOLUME (m3)", RegularExpression = @"^3161(\d{6})$" },
            new ApplicationIdentifier { Ai = "3162", Fnc1Required = false, DataTitle = "NET VOLUME (m3)", RegularExpression = @"^3162(\d{6})$" },
            new ApplicationIdentifier { Ai = "3163", Fnc1Required = false, DataTitle = "NET VOLUME (m3)", RegularExpression = @"^3163(\d{6})$" },
            new ApplicationIdentifier { Ai = "3164", Fnc1Required = false, DataTitle = "NET VOLUME (m3)", RegularExpression = @"^3164(\d{6})$" },
            new ApplicationIdentifier { Ai = "3165", Fnc1Required = false, DataTitle = "NET VOLUME (m3)", RegularExpression = @"^3165(\d{6})$" },
            new ApplicationIdentifier { Ai = "3200", Fnc1Required = false, DataTitle = "NET WEIGHT (lb)", RegularExpression = @"^3200(\d{6})$" },
            new ApplicationIdentifier { Ai = "3201", Fnc1Required = false, DataTitle = "NET WEIGHT (lb)", RegularExpression = @"^3201(\d{6})$" },
            new ApplicationIdentifier { Ai = "3202", Fnc1Required = false, DataTitle = "NET WEIGHT (lb)", RegularExpression = @"^3202(\d{6})$" },
            new ApplicationIdentifier { Ai = "3203", Fnc1Required = false, DataTitle = "NET WEIGHT (lb)", RegularExpression = @"^3203(\d{6})$" },
            new ApplicationIdentifier { Ai = "3204", Fnc1Required = false, DataTitle = "NET WEIGHT (lb)", RegularExpression = @"^3204(\d{6})$" },
            new ApplicationIdentifier { Ai = "3205", Fnc1Required = false, DataTitle = "NET WEIGHT (lb)", RegularExpression = @"^3205(\d{6})$" },
            new ApplicationIdentifier { Ai = "3210", Fnc1Required = false, DataTitle = "LENGTH (in)", RegularExpression = @"^3210(\d{6})$" },
            new ApplicationIdentifier { Ai = "3211", Fnc1Required = false, DataTitle = "LENGTH (in)", RegularExpression = @"^3211(\d{6})$" },
            new ApplicationIdentifier { Ai = "3212", Fnc1Required = false, DataTitle = "LENGTH (in)", RegularExpression = @"^3212(\d{6})$" },
            new ApplicationIdentifier { Ai = "3213", Fnc1Required = false, DataTitle = "LENGTH (in)", RegularExpression = @"^3213(\d{6})$" },
            new ApplicationIdentifier { Ai = "3214", Fnc1Required = false, DataTitle = "LENGTH (in)", RegularExpression = @"^3214(\d{6})$" },
            new ApplicationIdentifier { Ai = "3215", Fnc1Required = false, DataTitle = "LENGTH (in)", RegularExpression = @"^3215(\d{6})$" },
            new ApplicationIdentifier { Ai = "3220", Fnc1Required = false, DataTitle = "LENGTH (ft)", RegularExpression = @"^3220(\d{6})$" },
            new ApplicationIdentifier { Ai = "3221", Fnc1Required = false, DataTitle = "LENGTH (ft)", RegularExpression = @"^3221(\d{6})$" },
            new ApplicationIdentifier { Ai = "3222", Fnc1Required = false, DataTitle = "LENGTH (ft)", RegularExpression = @"^3222(\d{6})$" },
            new ApplicationIdentifier { Ai = "3223", Fnc1Required = false, DataTitle = "LENGTH (ft)", RegularExpression = @"^3223(\d{6})$" },
            new ApplicationIdentifier { Ai = "3224", Fnc1Required = false, DataTitle = "LENGTH (ft)", RegularExpression = @"^3224(\d{6})$" },
            new ApplicationIdentifier { Ai = "3225", Fnc1Required = false, DataTitle = "LENGTH (ft)", RegularExpression = @"^3225(\d{6})$" },
            new ApplicationIdentifier { Ai = "3230", Fnc1Required = false, DataTitle = "LENGTH (yd)", RegularExpression = @"^3230(\d{6})$" },
            new ApplicationIdentifier { Ai = "3231", Fnc1Required = false, DataTitle = "LENGTH (yd)", RegularExpression = @"^3231(\d{6})$" },
            new ApplicationIdentifier { Ai = "3232", Fnc1Required = false, DataTitle = "LENGTH (yd)", RegularExpression = @"^3232(\d{6})$" },
            new ApplicationIdentifier { Ai = "3233", Fnc1Required = false, DataTitle = "LENGTH (yd)", RegularExpression = @"^3233(\d{6})$" },
            new ApplicationIdentifier { Ai = "3234", Fnc1Required = false, DataTitle = "LENGTH (yd)", RegularExpression = @"^3234(\d{6})$" },
            new ApplicationIdentifier { Ai = "3235", Fnc1Required = false, DataTitle = "LENGTH (yd)", RegularExpression = @"^3235(\d{6})$" },
            new ApplicationIdentifier { Ai = "3240", Fnc1Required = false, DataTitle = "WIDTH (in)", RegularExpression = @"^3240(\d{6})$" },
            new ApplicationIdentifier { Ai = "3241", Fnc1Required = false, DataTitle = "WIDTH (in)", RegularExpression = @"^3241(\d{6})$" },
            new ApplicationIdentifier { Ai = "3242", Fnc1Required = false, DataTitle = "WIDTH (in)", RegularExpression = @"^3242(\d{6})$" },
            new ApplicationIdentifier { Ai = "3243", Fnc1Required = false, DataTitle = "WIDTH (in)", RegularExpression = @"^3243(\d{6})$" },
            new ApplicationIdentifier { Ai = "3244", Fnc1Required = false, DataTitle = "WIDTH (in)", RegularExpression = @"^3244(\d{6})$" },
            new ApplicationIdentifier { Ai = "3245", Fnc1Required = false, DataTitle = "WIDTH (in)", RegularExpression = @"^3245(\d{6})$" },
            new ApplicationIdentifier { Ai = "3250", Fnc1Required = false, DataTitle = "WIDTH (ft)", RegularExpression = @"^3250(\d{6})$" },
            new ApplicationIdentifier { Ai = "3251", Fnc1Required = false, DataTitle = "WIDTH (ft)", RegularExpression = @"^3251(\d{6})$" },
            new ApplicationIdentifier { Ai = "3252", Fnc1Required = false, DataTitle = "WIDTH (ft)", RegularExpression = @"^3252(\d{6})$" },
            new ApplicationIdentifier { Ai = "3253", Fnc1Required = false, DataTitle = "WIDTH (ft)", RegularExpression = @"^3253(\d{6})$" },
            new ApplicationIdentifier { Ai = "3254", Fnc1Required = false, DataTitle = "WIDTH (ft)", RegularExpression = @"^3254(\d{6})$" },
            new ApplicationIdentifier { Ai = "3255", Fnc1Required = false, DataTitle = "WIDTH (ft)", RegularExpression = @"^3255(\d{6})$" },
            new ApplicationIdentifier { Ai = "3260", Fnc1Required = false, DataTitle = "WIDTH (yd)", RegularExpression = @"^3260(\d{6})$" },
            new ApplicationIdentifier { Ai = "3261", Fnc1Required = false, DataTitle = "WIDTH (yd)", RegularExpression = @"^3261(\d{6})$" },
            new ApplicationIdentifier { Ai = "3262", Fnc1Required = false, DataTitle = "WIDTH (yd)", RegularExpression = @"^3262(\d{6})$" },
            new ApplicationIdentifier { Ai = "3263", Fnc1Required = false, DataTitle = "WIDTH (yd)", RegularExpression = @"^3263(\d{6})$" },
            new ApplicationIdentifier { Ai = "3264", Fnc1Required = false, DataTitle = "WIDTH (yd)", RegularExpression = @"^3264(\d{6})$" },
            new ApplicationIdentifier { Ai = "3265", Fnc1Required = false, DataTitle = "WIDTH (yd)", RegularExpression = @"^3265(\d{6})$" },
            new ApplicationIdentifier { Ai = "3270", Fnc1Required = false, DataTitle = "HEIGHT (in)", RegularExpression = @"^3270(\d{6})$" },
            new ApplicationIdentifier { Ai = "3271", Fnc1Required = false, DataTitle = "HEIGHT (in)", RegularExpression = @"^3271(\d{6})$" },
            new ApplicationIdentifier { Ai = "3272", Fnc1Required = false, DataTitle = "HEIGHT (in)", RegularExpression = @"^3272(\d{6})$" },
            new ApplicationIdentifier { Ai = "3273", Fnc1Required = false, DataTitle = "HEIGHT (in)", RegularExpression = @"^3273(\d{6})$" },
            new ApplicationIdentifier { Ai = "3274", Fnc1Required = false, DataTitle = "HEIGHT (in)", RegularExpression = @"^3274(\d{6})$" },
            new ApplicationIdentifier { Ai = "3275", Fnc1Required = false, DataTitle = "HEIGHT (in)", RegularExpression = @"^3275(\d{6})$" },
            new ApplicationIdentifier { Ai = "3280", Fnc1Required = false, DataTitle = "HEIGHT (ft)", RegularExpression = @"^3280(\d{6})$" },
            new ApplicationIdentifier { Ai = "3281", Fnc1Required = false, DataTitle = "HEIGHT (ft)", RegularExpression = @"^3281(\d{6})$" },
            new ApplicationIdentifier { Ai = "3282", Fnc1Required = false, DataTitle = "HEIGHT (ft)", RegularExpression = @"^3282(\d{6})$" },
            new ApplicationIdentifier { Ai = "3283", Fnc1Required = false, DataTitle = "HEIGHT (ft)", RegularExpression = @"^3283(\d{6})$" },
            new ApplicationIdentifier { Ai = "3284", Fnc1Required = false, DataTitle = "HEIGHT (ft)", RegularExpression = @"^3284(\d{6})$" },
            new ApplicationIdentifier { Ai = "3285", Fnc1Required = false, DataTitle = "HEIGHT (ft)", RegularExpression = @"^3285(\d{6})$" },
            new ApplicationIdentifier { Ai = "3290", Fnc1Required = false, DataTitle = "HEIGHT (yd)", RegularExpression = @"^3290(\d{6})$" },
            new ApplicationIdentifier { Ai = "3291", Fnc1Required = false, DataTitle = "HEIGHT (yd)", RegularExpression = @"^3291(\d{6})$" },
            new ApplicationIdentifier { Ai = "3292", Fnc1Required = false, DataTitle = "HEIGHT (yd)", RegularExpression = @"^3292(\d{6})$" },
            new ApplicationIdentifier { Ai = "3293", Fnc1Required = false, DataTitle = "HEIGHT (yd)", RegularExpression = @"^3293(\d{6})$" },
            new ApplicationIdentifier { Ai = "3294", Fnc1Required = false, DataTitle = "HEIGHT (yd)", RegularExpression = @"^3294(\d{6})$" },
            new ApplicationIdentifier { Ai = "3295", Fnc1Required = false, DataTitle = "HEIGHT (yd)", RegularExpression = @"^3295(\d{6})$" },
            new ApplicationIdentifier { Ai = "3300", Fnc1Required = false, DataTitle = "GROSS WEIGHT (kg)", RegularExpression = @"^3300(\d{6})$" },
            new ApplicationIdentifier { Ai = "3301", Fnc1Required = false, DataTitle = "GROSS WEIGHT (kg)", RegularExpression = @"^3301(\d{6})$" },
            new ApplicationIdentifier { Ai = "3302", Fnc1Required = false, DataTitle = "GROSS WEIGHT (kg)", RegularExpression = @"^3302(\d{6})$" },
            new ApplicationIdentifier { Ai = "3303", Fnc1Required = false, DataTitle = "GROSS WEIGHT (kg)", RegularExpression = @"^3303(\d{6})$" },
            new ApplicationIdentifier { Ai = "3304", Fnc1Required = false, DataTitle = "GROSS WEIGHT (kg)", RegularExpression = @"^3304(\d{6})$" },
            new ApplicationIdentifier { Ai = "3305", Fnc1Required = false, DataTitle = "GROSS WEIGHT (kg)", RegularExpression = @"^3305(\d{6})$" },
            new ApplicationIdentifier { Ai = "3310", Fnc1Required = false, DataTitle = "LENGTH (m), log", RegularExpression = @"^3310(\d{6})$" },
            new ApplicationIdentifier { Ai = "3311", Fnc1Required = false, DataTitle = "LENGTH (m), log", RegularExpression = @"^3311(\d{6})$" },
            new ApplicationIdentifier { Ai = "3312", Fnc1Required = false, DataTitle = "LENGTH (m), log", RegularExpression = @"^3312(\d{6})$" },
            new ApplicationIdentifier { Ai = "3313", Fnc1Required = false, DataTitle = "LENGTH (m), log", RegularExpression = @"^3313(\d{6})$" },
            new ApplicationIdentifier { Ai = "3314", Fnc1Required = false, DataTitle = "LENGTH (m), log", RegularExpression = @"^3314(\d{6})$" },
            new ApplicationIdentifier { Ai = "3315", Fnc1Required = false, DataTitle = "LENGTH (m), log", RegularExpression = @"^3315(\d{6})$" },
            new ApplicationIdentifier { Ai = "3320", Fnc1Required = false, DataTitle = "WIDTH (m), log", RegularExpression = @"^3320(\d{6})$" },
            new ApplicationIdentifier { Ai = "3321", Fnc1Required = false, DataTitle = "WIDTH (m), log", RegularExpression = @"^3321(\d{6})$" },
            new ApplicationIdentifier { Ai = "3322", Fnc1Required = false, DataTitle = "WIDTH (m), log", RegularExpression = @"^3322(\d{6})$" },
            new ApplicationIdentifier { Ai = "3323", Fnc1Required = false, DataTitle = "WIDTH (m), log", RegularExpression = @"^3323(\d{6})$" },
            new ApplicationIdentifier { Ai = "3324", Fnc1Required = false, DataTitle = "WIDTH (m), log", RegularExpression = @"^3324(\d{6})$" },
            new ApplicationIdentifier { Ai = "3325", Fnc1Required = false, DataTitle = "WIDTH (m), log", RegularExpression = @"^3325(\d{6})$" },
            new ApplicationIdentifier { Ai = "3330", Fnc1Required = false, DataTitle = "HEIGHT (m), log", RegularExpression = @"^3330(\d{6})$" },
            new ApplicationIdentifier { Ai = "3331", Fnc1Required = false, DataTitle = "HEIGHT (m), log", RegularExpression = @"^3331(\d{6})$" },
            new ApplicationIdentifier { Ai = "3332", Fnc1Required = false, DataTitle = "HEIGHT (m), log", RegularExpression = @"^3332(\d{6})$" },
            new ApplicationIdentifier { Ai = "3333", Fnc1Required = false, DataTitle = "HEIGHT (m), log", RegularExpression = @"^3333(\d{6})$" },
            new ApplicationIdentifier { Ai = "3334", Fnc1Required = false, DataTitle = "HEIGHT (m), log", RegularExpression = @"^3334(\d{6})$" },
            new ApplicationIdentifier { Ai = "3335", Fnc1Required = false, DataTitle = "HEIGHT (m), log", RegularExpression = @"^3335(\d{6})$" },
            new ApplicationIdentifier { Ai = "3340", Fnc1Required = false, DataTitle = "AREA (m2), log", RegularExpression = @"^3340(\d{6})$" },
            new ApplicationIdentifier { Ai = "3341", Fnc1Required = false, DataTitle = "AREA (m2), log", RegularExpression = @"^3341(\d{6})$" },
            new ApplicationIdentifier { Ai = "3342", Fnc1Required = false, DataTitle = "AREA (m2), log", RegularExpression = @"^3342(\d{6})$" },
            new ApplicationIdentifier { Ai = "3343", Fnc1Required = false, DataTitle = "AREA (m2), log", RegularExpression = @"^3343(\d{6})$" },
            new ApplicationIdentifier { Ai = "3344", Fnc1Required = false, DataTitle = "AREA (m2), log", RegularExpression = @"^3344(\d{6})$" },
            new ApplicationIdentifier { Ai = "3345", Fnc1Required = false, DataTitle = "AREA (m2), log", RegularExpression = @"^3345(\d{6})$" },
            new ApplicationIdentifier { Ai = "3350", Fnc1Required = false, DataTitle = "VOLUME (l), log", RegularExpression = @"^3350(\d{6})$" },
            new ApplicationIdentifier { Ai = "3351", Fnc1Required = false, DataTitle = "VOLUME (l), log", RegularExpression = @"^3351(\d{6})$" },
            new ApplicationIdentifier { Ai = "3352", Fnc1Required = false, DataTitle = "VOLUME (l), log", RegularExpression = @"^3352(\d{6})$" },
            new ApplicationIdentifier { Ai = "3353", Fnc1Required = false, DataTitle = "VOLUME (l), log", RegularExpression = @"^3353(\d{6})$" },
            new ApplicationIdentifier { Ai = "3354", Fnc1Required = false, DataTitle = "VOLUME (l), log", RegularExpression = @"^3354(\d{6})$" },
            new ApplicationIdentifier { Ai = "3355", Fnc1Required = false, DataTitle = "VOLUME (l), log", RegularExpression = @"^3355(\d{6})$" },
            new ApplicationIdentifier { Ai = "3360", Fnc1Required = false, DataTitle = "VOLUME (m3), log", RegularExpression = @"^3360(\d{6})$" },
            new ApplicationIdentifier { Ai = "3361", Fnc1Required = false, DataTitle = "VOLUME (m3), log", RegularExpression = @"^3361(\d{6})$" },
            new ApplicationIdentifier { Ai = "3362", Fnc1Required = false, DataTitle = "VOLUME (m3), log", RegularExpression = @"^3362(\d{6})$" },
            new ApplicationIdentifier { Ai = "3363", Fnc1Required = false, DataTitle = "VOLUME (m3), log", RegularExpression = @"^3363(\d{6})$" },
            new ApplicationIdentifier { Ai = "3364", Fnc1Required = false, DataTitle = "VOLUME (m3), log", RegularExpression = @"^3364(\d{6})$" },
            new ApplicationIdentifier { Ai = "3365", Fnc1Required = false, DataTitle = "VOLUME (m3), log", RegularExpression = @"^3365(\d{6})$" },
            new ApplicationIdentifier { Ai = "3370", Fnc1Required = false, DataTitle = "KG PER m2", RegularExpression = @"^3370(\d{6})$" },
            new ApplicationIdentifier { Ai = "3371", Fnc1Required = false, DataTitle = "KG PER m2", RegularExpression = @"^3371(\d{6})$" },
            new ApplicationIdentifier { Ai = "3372", Fnc1Required = false, DataTitle = "KG PER m2", RegularExpression = @"^3372(\d{6})$" },
            new ApplicationIdentifier { Ai = "3373", Fnc1Required = false, DataTitle = "KG PER m2", RegularExpression = @"^3373(\d{6})$" },
            new ApplicationIdentifier { Ai = "3374", Fnc1Required = false, DataTitle = "KG PER m2", RegularExpression = @"^3374(\d{6})$" },
            new ApplicationIdentifier { Ai = "3375", Fnc1Required = false, DataTitle = "KG PER m2", RegularExpression = @"^3375(\d{6})$" },
            new ApplicationIdentifier { Ai = "3400", Fnc1Required = false, DataTitle = "GROSS WEIGHT (lb)", RegularExpression = @"^3400(\d{6})$" },
            new ApplicationIdentifier { Ai = "3401", Fnc1Required = false, DataTitle = "GROSS WEIGHT (lb)", RegularExpression = @"^3401(\d{6})$" },
            new ApplicationIdentifier { Ai = "3402", Fnc1Required = false, DataTitle = "GROSS WEIGHT (lb)", RegularExpression = @"^3402(\d{6})$" },
            new ApplicationIdentifier { Ai = "3403", Fnc1Required = false, DataTitle = "GROSS WEIGHT (lb)", RegularExpression = @"^3403(\d{6})$" },
            new ApplicationIdentifier { Ai = "3404", Fnc1Required = false, DataTitle = "GROSS WEIGHT (lb)", RegularExpression = @"^3404(\d{6})$" },
            new ApplicationIdentifier { Ai = "3405", Fnc1Required = false, DataTitle = "GROSS WEIGHT (lb)", RegularExpression = @"^3405(\d{6})$" },
            new ApplicationIdentifier { Ai = "3410", Fnc1Required = false, DataTitle = "LENGTH (in), log", RegularExpression = @"^3410(\d{6})$" },
            new ApplicationIdentifier { Ai = "3411", Fnc1Required = false, DataTitle = "LENGTH (in), log", RegularExpression = @"^3411(\d{6})$" },
            new ApplicationIdentifier { Ai = "3412", Fnc1Required = false, DataTitle = "LENGTH (in), log", RegularExpression = @"^3412(\d{6})$" },
            new ApplicationIdentifier { Ai = "3413", Fnc1Required = false, DataTitle = "LENGTH (in), log", RegularExpression = @"^3413(\d{6})$" },
            new ApplicationIdentifier { Ai = "3414", Fnc1Required = false, DataTitle = "LENGTH (in), log", RegularExpression = @"^3414(\d{6})$" },
            new ApplicationIdentifier { Ai = "3415", Fnc1Required = false, DataTitle = "LENGTH (in), log", RegularExpression = @"^3415(\d{6})$" },
            new ApplicationIdentifier { Ai = "3420", Fnc1Required = false, DataTitle = "LENGTH (ft), log", RegularExpression = @"^3420(\d{6})$" },
            new ApplicationIdentifier { Ai = "3421", Fnc1Required = false, DataTitle = "LENGTH (ft), log", RegularExpression = @"^3421(\d{6})$" },
            new ApplicationIdentifier { Ai = "3422", Fnc1Required = false, DataTitle = "LENGTH (ft), log", RegularExpression = @"^3422(\d{6})$" },
            new ApplicationIdentifier { Ai = "3423", Fnc1Required = false, DataTitle = "LENGTH (ft), log", RegularExpression = @"^3423(\d{6})$" },
            new ApplicationIdentifier { Ai = "3424", Fnc1Required = false, DataTitle = "LENGTH (ft), log", RegularExpression = @"^3424(\d{6})$" },
            new ApplicationIdentifier { Ai = "3425", Fnc1Required = false, DataTitle = "LENGTH (ft), log", RegularExpression = @"^3425(\d{6})$" },
            new ApplicationIdentifier { Ai = "3430", Fnc1Required = false, DataTitle = "LENGTH (yd), log", RegularExpression = @"^3430(\d{6})$" },
            new ApplicationIdentifier { Ai = "3431", Fnc1Required = false, DataTitle = "LENGTH (yd), log", RegularExpression = @"^3431(\d{6})$" },
            new ApplicationIdentifier { Ai = "3432", Fnc1Required = false, DataTitle = "LENGTH (yd), log", RegularExpression = @"^3432(\d{6})$" },
            new ApplicationIdentifier { Ai = "3433", Fnc1Required = false, DataTitle = "LENGTH (yd), log", RegularExpression = @"^3433(\d{6})$" },
            new ApplicationIdentifier { Ai = "3434", Fnc1Required = false, DataTitle = "LENGTH (yd), log", RegularExpression = @"^3434(\d{6})$" },
            new ApplicationIdentifier { Ai = "3435", Fnc1Required = false, DataTitle = "LENGTH (yd), log", RegularExpression = @"^3435(\d{6})$" },
            new ApplicationIdentifier { Ai = "3440", Fnc1Required = false, DataTitle = "WIDTH (in), log", RegularExpression = @"^3440(\d{6})$" },
            new ApplicationIdentifier { Ai = "3441", Fnc1Required = false, DataTitle = "WIDTH (in), log", RegularExpression = @"^3441(\d{6})$" },
            new ApplicationIdentifier { Ai = "3442", Fnc1Required = false, DataTitle = "WIDTH (in), log", RegularExpression = @"^3442(\d{6})$" },
            new ApplicationIdentifier { Ai = "3443", Fnc1Required = false, DataTitle = "WIDTH (in), log", RegularExpression = @"^3443(\d{6})$" },
            new ApplicationIdentifier { Ai = "3444", Fnc1Required = false, DataTitle = "WIDTH (in), log", RegularExpression = @"^3444(\d{6})$" },
            new ApplicationIdentifier { Ai = "3445", Fnc1Required = false, DataTitle = "WIDTH (in), log", RegularExpression = @"^3445(\d{6})$" },
            new ApplicationIdentifier { Ai = "3450", Fnc1Required = false, DataTitle = "WIDTH (ft), log", RegularExpression = @"^3450(\d{6})$" },
            new ApplicationIdentifier { Ai = "3451", Fnc1Required = false, DataTitle = "WIDTH (ft), log", RegularExpression = @"^3451(\d{6})$" },
            new ApplicationIdentifier { Ai = "3452", Fnc1Required = false, DataTitle = "WIDTH (ft), log", RegularExpression = @"^3452(\d{6})$" },
            new ApplicationIdentifier { Ai = "3453", Fnc1Required = false, DataTitle = "WIDTH (ft), log", RegularExpression = @"^3453(\d{6})$" },
            new ApplicationIdentifier { Ai = "3454", Fnc1Required = false, DataTitle = "WIDTH (ft), log", RegularExpression = @"^3454(\d{6})$" },
            new ApplicationIdentifier { Ai = "3455", Fnc1Required = false, DataTitle = "WIDTH (ft), log", RegularExpression = @"^3455(\d{6})$" },
            new ApplicationIdentifier { Ai = "3460", Fnc1Required = false, DataTitle = "WIDTH (yd), log", RegularExpression = @"^3460(\d{6})$" },
            new ApplicationIdentifier { Ai = "3461", Fnc1Required = false, DataTitle = "WIDTH (yd), log", RegularExpression = @"^3461(\d{6})$" },
            new ApplicationIdentifier { Ai = "3462", Fnc1Required = false, DataTitle = "WIDTH (yd), log", RegularExpression = @"^3462(\d{6})$" },
            new ApplicationIdentifier { Ai = "3463", Fnc1Required = false, DataTitle = "WIDTH (yd), log", RegularExpression = @"^3463(\d{6})$" },
            new ApplicationIdentifier { Ai = "3464", Fnc1Required = false, DataTitle = "WIDTH (yd), log", RegularExpression = @"^3464(\d{6})$" },
            new ApplicationIdentifier { Ai = "3465", Fnc1Required = false, DataTitle = "WIDTH (yd), log", RegularExpression = @"^3465(\d{6})$" },
            new ApplicationIdentifier { Ai = "3470", Fnc1Required = false, DataTitle = "HEIGHT (in), log", RegularExpression = @"^3470(\d{6})$" },
            new ApplicationIdentifier { Ai = "3471", Fnc1Required = false, DataTitle = "HEIGHT (in), log", RegularExpression = @"^3471(\d{6})$" },
            new ApplicationIdentifier { Ai = "3472", Fnc1Required = false, DataTitle = "HEIGHT (in), log", RegularExpression = @"^3472(\d{6})$" },
            new ApplicationIdentifier { Ai = "3473", Fnc1Required = false, DataTitle = "HEIGHT (in), log", RegularExpression = @"^3473(\d{6})$" },
            new ApplicationIdentifier { Ai = "3474", Fnc1Required = false, DataTitle = "HEIGHT (in), log", RegularExpression = @"^3474(\d{6})$" },
            new ApplicationIdentifier { Ai = "3475", Fnc1Required = false, DataTitle = "HEIGHT (in), log", RegularExpression = @"^3475(\d{6})$" },
            new ApplicationIdentifier { Ai = "3480", Fnc1Required = false, DataTitle = "HEIGHT (ft), log", RegularExpression = @"^3480(\d{6})$" },
            new ApplicationIdentifier { Ai = "3481", Fnc1Required = false, DataTitle = "HEIGHT (ft), log", RegularExpression = @"^3481(\d{6})$" },
            new ApplicationIdentifier { Ai = "3482", Fnc1Required = false, DataTitle = "HEIGHT (ft), log", RegularExpression = @"^3482(\d{6})$" },
            new ApplicationIdentifier { Ai = "3483", Fnc1Required = false, DataTitle = "HEIGHT (ft), log", RegularExpression = @"^3483(\d{6})$" },
            new ApplicationIdentifier { Ai = "3484", Fnc1Required = false, DataTitle = "HEIGHT (ft), log", RegularExpression = @"^3484(\d{6})$" },
            new ApplicationIdentifier { Ai = "3485", Fnc1Required = false, DataTitle = "HEIGHT (ft), log", RegularExpression = @"^3485(\d{6})$" },
            new ApplicationIdentifier { Ai = "3490", Fnc1Required = false, DataTitle = "HEIGHT (yd), log", RegularExpression = @"^3490(\d{6})$" },
            new ApplicationIdentifier { Ai = "3491", Fnc1Required = false, DataTitle = "HEIGHT (yd), log", RegularExpression = @"^3491(\d{6})$" },
            new ApplicationIdentifier { Ai = "3492", Fnc1Required = false, DataTitle = "HEIGHT (yd), log", RegularExpression = @"^3492(\d{6})$" },
            new ApplicationIdentifier { Ai = "3493", Fnc1Required = false, DataTitle = "HEIGHT (yd), log", RegularExpression = @"^3493(\d{6})$" },
            new ApplicationIdentifier { Ai = "3494", Fnc1Required = false, DataTitle = "HEIGHT (yd), log", RegularExpression = @"^3494(\d{6})$" },
            new ApplicationIdentifier { Ai = "3495", Fnc1Required = false, DataTitle = "HEIGHT (yd), log", RegularExpression = @"^3495(\d{6})$" },
            new ApplicationIdentifier { Ai = "3500", Fnc1Required = false, DataTitle = "AREA (in2)", RegularExpression = @"^3500(\d{6})$" },
            new ApplicationIdentifier { Ai = "3501", Fnc1Required = false, DataTitle = "AREA (in2)", RegularExpression = @"^3501(\d{6})$" },
            new ApplicationIdentifier { Ai = "3502", Fnc1Required = false, DataTitle = "AREA (in2)", RegularExpression = @"^3502(\d{6})$" },
            new ApplicationIdentifier { Ai = "3503", Fnc1Required = false, DataTitle = "AREA (in2)", RegularExpression = @"^3503(\d{6})$" },
            new ApplicationIdentifier { Ai = "3504", Fnc1Required = false, DataTitle = "AREA (in2)", RegularExpression = @"^3504(\d{6})$" },
            new ApplicationIdentifier { Ai = "3505", Fnc1Required = false, DataTitle = "AREA (in2)", RegularExpression = @"^3505(\d{6})$" },
            new ApplicationIdentifier { Ai = "3510", Fnc1Required = false, DataTitle = "AREA (ft2)", RegularExpression = @"^3510(\d{6})$" },
            new ApplicationIdentifier { Ai = "3511", Fnc1Required = false, DataTitle = "AREA (ft2)", RegularExpression = @"^3511(\d{6})$" },
            new ApplicationIdentifier { Ai = "3512", Fnc1Required = false, DataTitle = "AREA (ft2)", RegularExpression = @"^3512(\d{6})$" },
            new ApplicationIdentifier { Ai = "3513", Fnc1Required = false, DataTitle = "AREA (ft2)", RegularExpression = @"^3513(\d{6})$" },
            new ApplicationIdentifier { Ai = "3514", Fnc1Required = false, DataTitle = "AREA (ft2)", RegularExpression = @"^3514(\d{6})$" },
            new ApplicationIdentifier { Ai = "3515", Fnc1Required = false, DataTitle = "AREA (ft2)", RegularExpression = @"^3515(\d{6})$" },
            new ApplicationIdentifier { Ai = "3520", Fnc1Required = false, DataTitle = "AREA (yd2)", RegularExpression = @"^3520(\d{6})$" },
            new ApplicationIdentifier { Ai = "3521", Fnc1Required = false, DataTitle = "AREA (yd2)", RegularExpression = @"^3521(\d{6})$" },
            new ApplicationIdentifier { Ai = "3522", Fnc1Required = false, DataTitle = "AREA (yd2)", RegularExpression = @"^3522(\d{6})$" },
            new ApplicationIdentifier { Ai = "3523", Fnc1Required = false, DataTitle = "AREA (yd2)", RegularExpression = @"^3523(\d{6})$" },
            new ApplicationIdentifier { Ai = "3524", Fnc1Required = false, DataTitle = "AREA (yd2)", RegularExpression = @"^3524(\d{6})$" },
            new ApplicationIdentifier { Ai = "3525", Fnc1Required = false, DataTitle = "AREA (yd2)", RegularExpression = @"^3525(\d{6})$" },
            new ApplicationIdentifier { Ai = "3530", Fnc1Required = false, DataTitle = "AREA (in2), log", RegularExpression = @"^3530(\d{6})$" },
            new ApplicationIdentifier { Ai = "3531", Fnc1Required = false, DataTitle = "AREA (in2), log", RegularExpression = @"^3531(\d{6})$" },
            new ApplicationIdentifier { Ai = "3532", Fnc1Required = false, DataTitle = "AREA (in2), log", RegularExpression = @"^3532(\d{6})$" },
            new ApplicationIdentifier { Ai = "3533", Fnc1Required = false, DataTitle = "AREA (in2), log", RegularExpression = @"^3533(\d{6})$" },
            new ApplicationIdentifier { Ai = "3534", Fnc1Required = false, DataTitle = "AREA (in2), log", RegularExpression = @"^3534(\d{6})$" },
            new ApplicationIdentifier { Ai = "3535", Fnc1Required = false, DataTitle = "AREA (in2), log", RegularExpression = @"^3535(\d{6})$" },
            new ApplicationIdentifier { Ai = "3540", Fnc1Required = false, DataTitle = "AREA (ft2), log", RegularExpression = @"^3540(\d{6})$" },
            new ApplicationIdentifier { Ai = "3541", Fnc1Required = false, DataTitle = "AREA (ft2), log", RegularExpression = @"^3541(\d{6})$" },
            new ApplicationIdentifier { Ai = "3542", Fnc1Required = false, DataTitle = "AREA (ft2), log", RegularExpression = @"^3542(\d{6})$" },
            new ApplicationIdentifier { Ai = "3543", Fnc1Required = false, DataTitle = "AREA (ft2), log", RegularExpression = @"^3543(\d{6})$" },
            new ApplicationIdentifier { Ai = "3544", Fnc1Required = false, DataTitle = "AREA (ft2), log", RegularExpression = @"^3544(\d{6})$" },
            new ApplicationIdentifier { Ai = "3545", Fnc1Required = false, DataTitle = "AREA (ft2), log", RegularExpression = @"^3545(\d{6})$" },
            new ApplicationIdentifier { Ai = "3550", Fnc1Required = false, DataTitle = "AREA (yd2), log", RegularExpression = @"^3550(\d{6})$" },
            new ApplicationIdentifier { Ai = "3551", Fnc1Required = false, DataTitle = "AREA (yd2), log", RegularExpression = @"^3551(\d{6})$" },
            new ApplicationIdentifier { Ai = "3552", Fnc1Required = false, DataTitle = "AREA (yd2), log", RegularExpression = @"^3552(\d{6})$" },
            new ApplicationIdentifier { Ai = "3553", Fnc1Required = false, DataTitle = "AREA (yd2), log", RegularExpression = @"^3553(\d{6})$" },
            new ApplicationIdentifier { Ai = "3554", Fnc1Required = false, DataTitle = "AREA (yd2), log", RegularExpression = @"^3554(\d{6})$" },
            new ApplicationIdentifier { Ai = "3555", Fnc1Required = false, DataTitle = "AREA (yd2), log", RegularExpression = @"^3555(\d{6})$" },
            new ApplicationIdentifier { Ai = "3560", Fnc1Required = false, DataTitle = "NET WEIGHT (t oz)", RegularExpression = @"^3560(\d{6})$" },
            new ApplicationIdentifier { Ai = "3561", Fnc1Required = false, DataTitle = "NET WEIGHT (t oz)", RegularExpression = @"^3561(\d{6})$" },
            new ApplicationIdentifier { Ai = "3562", Fnc1Required = false, DataTitle = "NET WEIGHT (t oz)", RegularExpression = @"^3562(\d{6})$" },
            new ApplicationIdentifier { Ai = "3563", Fnc1Required = false, DataTitle = "NET WEIGHT (t oz)", RegularExpression = @"^3563(\d{6})$" },
            new ApplicationIdentifier { Ai = "3564", Fnc1Required = false, DataTitle = "NET WEIGHT (t oz)", RegularExpression = @"^3564(\d{6})$" },
            new ApplicationIdentifier { Ai = "3565", Fnc1Required = false, DataTitle = "NET WEIGHT (t oz)", RegularExpression = @"^3565(\d{6})$" },
            new ApplicationIdentifier { Ai = "3570", Fnc1Required = false, DataTitle = "NET VOLUME (oz)", RegularExpression = @"^3570(\d{6})$" },
            new ApplicationIdentifier { Ai = "3571", Fnc1Required = false, DataTitle = "NET VOLUME (oz)", RegularExpression = @"^3571(\d{6})$" },
            new ApplicationIdentifier { Ai = "3572", Fnc1Required = false, DataTitle = "NET VOLUME (oz)", RegularExpression = @"^3572(\d{6})$" },
            new ApplicationIdentifier { Ai = "3573", Fnc1Required = false, DataTitle = "NET VOLUME (oz)", RegularExpression = @"^3573(\d{6})$" },
            new ApplicationIdentifier { Ai = "3574", Fnc1Required = false, DataTitle = "NET VOLUME (oz)", RegularExpression = @"^3574(\d{6})$" },
            new ApplicationIdentifier { Ai = "3575", Fnc1Required = false, DataTitle = "NET VOLUME (oz)", RegularExpression = @"^3575(\d{6})$" },
            new ApplicationIdentifier { Ai = "3600", Fnc1Required = false, DataTitle = "NET VOLUME (qt)", RegularExpression = @"^3600(\d{6})$" },
            new ApplicationIdentifier { Ai = "3601", Fnc1Required = false, DataTitle = "NET VOLUME (qt)", RegularExpression = @"^3601(\d{6})$" },
            new ApplicationIdentifier { Ai = "3602", Fnc1Required = false, DataTitle = "NET VOLUME (qt)", RegularExpression = @"^3602(\d{6})$" },
            new ApplicationIdentifier { Ai = "3603", Fnc1Required = false, DataTitle = "NET VOLUME (qt)", RegularExpression = @"^3603(\d{6})$" },
            new ApplicationIdentifier { Ai = "3604", Fnc1Required = false, DataTitle = "NET VOLUME (qt)", RegularExpression = @"^3604(\d{6})$" },
            new ApplicationIdentifier { Ai = "3605", Fnc1Required = false, DataTitle = "NET VOLUME (qt)", RegularExpression = @"^3605(\d{6})$" },
            new ApplicationIdentifier { Ai = "3610", Fnc1Required = false, DataTitle = "NET VOLUME (gal.)", RegularExpression = @"^3610(\d{6})$" },
            new ApplicationIdentifier { Ai = "3611", Fnc1Required = false, DataTitle = "NET VOLUME (gal.)", RegularExpression = @"^3611(\d{6})$" },
            new ApplicationIdentifier { Ai = "3612", Fnc1Required = false, DataTitle = "NET VOLUME (gal.)", RegularExpression = @"^3612(\d{6})$" },
            new ApplicationIdentifier { Ai = "3613", Fnc1Required = false, DataTitle = "NET VOLUME (gal.)", RegularExpression = @"^3613(\d{6})$" },
            new ApplicationIdentifier { Ai = "3614", Fnc1Required = false, DataTitle = "NET VOLUME (gal.)", RegularExpression = @"^3614(\d{6})$" },
            new ApplicationIdentifier { Ai = "3615", Fnc1Required = false, DataTitle = "NET VOLUME (gal.)", RegularExpression = @"^3615(\d{6})$" },
            new ApplicationIdentifier { Ai = "3620", Fnc1Required = false, DataTitle = "VOLUME (qt), log", RegularExpression = @"^3620(\d{6})$" },
            new ApplicationIdentifier { Ai = "3621", Fnc1Required = false, DataTitle = "VOLUME (qt), log", RegularExpression = @"^3621(\d{6})$" },
            new ApplicationIdentifier { Ai = "3622", Fnc1Required = false, DataTitle = "VOLUME (qt), log", RegularExpression = @"^3622(\d{6})$" },
            new ApplicationIdentifier { Ai = "3623", Fnc1Required = false, DataTitle = "VOLUME (qt), log", RegularExpression = @"^3623(\d{6})$" },
            new ApplicationIdentifier { Ai = "3624", Fnc1Required = false, DataTitle = "VOLUME (qt), log", RegularExpression = @"^3624(\d{6})$" },
            new ApplicationIdentifier { Ai = "3625", Fnc1Required = false, DataTitle = "VOLUME (qt), log", RegularExpression = @"^3625(\d{6})$" },
            new ApplicationIdentifier { Ai = "3630", Fnc1Required = false, DataTitle = "VOLUME (gal.), log", RegularExpression = @"^3630(\d{6})$" },
            new ApplicationIdentifier { Ai = "3631", Fnc1Required = false, DataTitle = "VOLUME (gal.), log", RegularExpression = @"^3631(\d{6})$" },
            new ApplicationIdentifier { Ai = "3632", Fnc1Required = false, DataTitle = "VOLUME (gal.), log", RegularExpression = @"^3632(\d{6})$" },
            new ApplicationIdentifier { Ai = "3633", Fnc1Required = false, DataTitle = "VOLUME (gal.), log", RegularExpression = @"^3633(\d{6})$" },
            new ApplicationIdentifier { Ai = "3634", Fnc1Required = false, DataTitle = "VOLUME (gal.), log", RegularExpression = @"^3634(\d{6})$" },
            new ApplicationIdentifier { Ai = "3635", Fnc1Required = false, DataTitle = "VOLUME (gal.), log", RegularExpression = @"^3635(\d{6})$" },
            new ApplicationIdentifier { Ai = "3640", Fnc1Required = false, DataTitle = "VOLUME (in3)", RegularExpression = @"^3640(\d{6})$" },
            new ApplicationIdentifier { Ai = "3641", Fnc1Required = false, DataTitle = "VOLUME (in3)", RegularExpression = @"^3641(\d{6})$" },
            new ApplicationIdentifier { Ai = "3642", Fnc1Required = false, DataTitle = "VOLUME (in3)", RegularExpression = @"^3642(\d{6})$" },
            new ApplicationIdentifier { Ai = "3643", Fnc1Required = false, DataTitle = "VOLUME (in3)", RegularExpression = @"^3643(\d{6})$" },
            new ApplicationIdentifier { Ai = "3644", Fnc1Required = false, DataTitle = "VOLUME (in3)", RegularExpression = @"^3644(\d{6})$" },
            new ApplicationIdentifier { Ai = "3645", Fnc1Required = false, DataTitle = "VOLUME (in3)", RegularExpression = @"^3645(\d{6})$" },
            new ApplicationIdentifier { Ai = "3650", Fnc1Required = false, DataTitle = "VOLUME (ft3)", RegularExpression = @"^3650(\d{6})$" },
            new ApplicationIdentifier { Ai = "3651", Fnc1Required = false, DataTitle = "VOLUME (ft3)", RegularExpression = @"^3651(\d{6})$" },
            new ApplicationIdentifier { Ai = "3652", Fnc1Required = false, DataTitle = "VOLUME (ft3)", RegularExpression = @"^3652(\d{6})$" },
            new ApplicationIdentifier { Ai = "3653", Fnc1Required = false, DataTitle = "VOLUME (ft3)", RegularExpression = @"^3653(\d{6})$" },
            new ApplicationIdentifier { Ai = "3654", Fnc1Required = false, DataTitle = "VOLUME (ft3)", RegularExpression = @"^3654(\d{6})$" },
            new ApplicationIdentifier { Ai = "3655", Fnc1Required = false, DataTitle = "VOLUME (ft3)", RegularExpression = @"^3655(\d{6})$" },
            new ApplicationIdentifier { Ai = "3660", Fnc1Required = false, DataTitle = "VOLUME (yd3)", RegularExpression = @"^3660(\d{6})$" },
            new ApplicationIdentifier { Ai = "3661", Fnc1Required = false, DataTitle = "VOLUME (yd3)", RegularExpression = @"^3661(\d{6})$" },
            new ApplicationIdentifier { Ai = "3662", Fnc1Required = false, DataTitle = "VOLUME (yd3)", RegularExpression = @"^3662(\d{6})$" },
            new ApplicationIdentifier { Ai = "3663", Fnc1Required = false, DataTitle = "VOLUME (yd3)", RegularExpression = @"^3663(\d{6})$" },
            new ApplicationIdentifier { Ai = "3664", Fnc1Required = false, DataTitle = "VOLUME (yd3)", RegularExpression = @"^3664(\d{6})$" },
            new ApplicationIdentifier { Ai = "3665", Fnc1Required = false, DataTitle = "VOLUME (yd3)", RegularExpression = @"^3665(\d{6})$" },
            new ApplicationIdentifier { Ai = "3670", Fnc1Required = false, DataTitle = "VOLUME (in3), log", RegularExpression = @"^3670(\d{6})$" },
            new ApplicationIdentifier { Ai = "3671", Fnc1Required = false, DataTitle = "VOLUME (in3), log", RegularExpression = @"^3671(\d{6})$" },
            new ApplicationIdentifier { Ai = "3672", Fnc1Required = false, DataTitle = "VOLUME (in3), log", RegularExpression = @"^3672(\d{6})$" },
            new ApplicationIdentifier { Ai = "3673", Fnc1Required = false, DataTitle = "VOLUME (in3), log", RegularExpression = @"^3673(\d{6})$" },
            new ApplicationIdentifier { Ai = "3674", Fnc1Required = false, DataTitle = "VOLUME (in3), log", RegularExpression = @"^3674(\d{6})$" },
            new ApplicationIdentifier { Ai = "3675", Fnc1Required = false, DataTitle = "VOLUME (in3), log", RegularExpression = @"^3675(\d{6})$" },
            new ApplicationIdentifier { Ai = "3680", Fnc1Required = false, DataTitle = "VOLUME (ft3), log", RegularExpression = @"^3680(\d{6})$" },
            new ApplicationIdentifier { Ai = "3681", Fnc1Required = false, DataTitle = "VOLUME (ft3), log", RegularExpression = @"^3681(\d{6})$" },
            new ApplicationIdentifier { Ai = "3682", Fnc1Required = false, DataTitle = "VOLUME (ft3), log", RegularExpression = @"^3682(\d{6})$" },
            new ApplicationIdentifier { Ai = "3683", Fnc1Required = false, DataTitle = "VOLUME (ft3), log", RegularExpression = @"^3683(\d{6})$" },
            new ApplicationIdentifier { Ai = "3684", Fnc1Required = false, DataTitle = "VOLUME (ft3), log", RegularExpression = @"^3684(\d{6})$" },
            new ApplicationIdentifier { Ai = "3685", Fnc1Required = false, DataTitle = "VOLUME (ft3), log", RegularExpression = @"^3685(\d{6})$" },
            new ApplicationIdentifier { Ai = "3690", Fnc1Required = false, DataTitle = "VOLUME (yd3), log", RegularExpression = @"^3690(\d{6})$" },
            new ApplicationIdentifier { Ai = "3691", Fnc1Required = false, DataTitle = "VOLUME (yd3), log", RegularExpression = @"^3691(\d{6})$" },
            new ApplicationIdentifier { Ai = "3692", Fnc1Required = false, DataTitle = "VOLUME (yd3), log", RegularExpression = @"^3692(\d{6})$" },
            new ApplicationIdentifier { Ai = "3693", Fnc1Required = false, DataTitle = "VOLUME (yd3), log", RegularExpression = @"^3693(\d{6})$" },
            new ApplicationIdentifier { Ai = "3694", Fnc1Required = false, DataTitle = "VOLUME (yd3), log", RegularExpression = @"^3694(\d{6})$" },
            new ApplicationIdentifier { Ai = "3695", Fnc1Required = false, DataTitle = "VOLUME (yd3), log", RegularExpression = @"^3695(\d{6})$" },
            new ApplicationIdentifier { Ai = "37", Fnc1Required = true, DataTitle = "COUNT", RegularExpression = @"^37(\d{0,8})$" },
            new ApplicationIdentifier { Ai = "3900", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3900(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3901", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3901(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3902", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3902(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3903", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3903(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3904", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3904(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3905", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3905(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3906", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3906(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3907", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3907(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3908", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3908(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3909", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3909(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3910", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3910(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3911", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3911(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3912", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3912(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3913", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3913(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3914", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3914(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3915", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3915(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3916", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3916(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3917", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3917(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3918", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3918(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3919", Fnc1Required = true, DataTitle = "AMOUNT", RegularExpression = @"^3919(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3920", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3920(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3921", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3921(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3922", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3922(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3923", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3923(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3924", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3924(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3925", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3925(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3926", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3926(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3927", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3927(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3928", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3928(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3929", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3929(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3930", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3930(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3931", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3931(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3932", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3932(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3933", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3933(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3934", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3934(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3935", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3935(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3936", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3936(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3937", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3937(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3938", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3938(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3939", Fnc1Required = true, DataTitle = "PRICE", RegularExpression = @"^3939(\d{3})(\d{0,15})$" },
            new ApplicationIdentifier { Ai = "3940", Fnc1Required = true, DataTitle = "PRCNT OFF", RegularExpression = @"^3940(\d{4})$" },
            new ApplicationIdentifier { Ai = "3941", Fnc1Required = true, DataTitle = "PRCNT OFF", RegularExpression = @"^3941(\d{4})$" },
            new ApplicationIdentifier { Ai = "3942", Fnc1Required = true, DataTitle = "PRCNT OFF", RegularExpression = @"^3942(\d{4})$" },
            new ApplicationIdentifier { Ai = "3943", Fnc1Required = true, DataTitle = "PRCNT OFF", RegularExpression = @"^3943(\d{4})$" },
            new ApplicationIdentifier { Ai = "400", Fnc1Required = true, DataTitle = "ORDER NUMBER", RegularExpression = @"^400([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "401", Fnc1Required = true, DataTitle = "GINC", RegularExpression = @"^401([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "402", Fnc1Required = true, DataTitle = "GSIN", RegularExpression = @"^402(\d{17})$" },
            new ApplicationIdentifier { Ai = "403", Fnc1Required = true, DataTitle = "ROUTE", RegularExpression = @"^403([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "410", Fnc1Required = false, DataTitle = "SHIP TO LOC", RegularExpression = @"^410(\d{13})$" },
            new ApplicationIdentifier { Ai = "411", Fnc1Required = false, DataTitle = "BILL TO", RegularExpression = @"^411(\d{13})$" },
            new ApplicationIdentifier { Ai = "412", Fnc1Required = false, DataTitle = "PURCHASE FROM", RegularExpression = @"^412(\d{13})$" },
            new ApplicationIdentifier { Ai = "413", Fnc1Required = false, DataTitle = "SHIP FOR LOC", RegularExpression = @"^413(\d{13})$" },
            new ApplicationIdentifier { Ai = "414", Fnc1Required = false, DataTitle = "LOC No", RegularExpression = @"^414(\d{13})$" },
            new ApplicationIdentifier { Ai = "415", Fnc1Required = false, DataTitle = "PAY TO", RegularExpression = @"^415(\d{13})$" },
            new ApplicationIdentifier { Ai = "416", Fnc1Required = false, DataTitle = "PROD/SERV LOC", RegularExpression = @"^416(\d{13})$" },
            new ApplicationIdentifier { Ai = "417", Fnc1Required = false, DataTitle = "PARTY", RegularExpression = @"417(\d{13})$" },
            new ApplicationIdentifier { Ai = "420", Fnc1Required = true, DataTitle = "SHIP TO POST", RegularExpression = @"^420([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "421", Fnc1Required = true, DataTitle = "SHIP TO POST", RegularExpression = @"^421(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,9})$" },
            new ApplicationIdentifier { Ai = "422", Fnc1Required = true, DataTitle = "ORIGIN", RegularExpression = @"^422(\d{3})$" },
            new ApplicationIdentifier { Ai = "423", Fnc1Required = true, DataTitle = "COUNTRY - INITIAL PROCESS.", RegularExpression = @"^423(\d{3})(\d{0,12})$" },
            new ApplicationIdentifier { Ai = "424", Fnc1Required = true, DataTitle = "COUNTRY - PROCESS.", RegularExpression = @"^424(\d{3})$" },
            new ApplicationIdentifier { Ai = "425", Fnc1Required = true, DataTitle = "COUNTRY - DISASSEMBLY", RegularExpression = @"^425(\d{3})(\d{0,12})$" },
            new ApplicationIdentifier { Ai = "426", Fnc1Required = true, DataTitle = "COUNTRY - FULL PROCESS", RegularExpression = @"^426(\d{3})$" },
            new ApplicationIdentifier { Ai = "427", Fnc1Required = true, DataTitle = "ORIGIN SUBDIVISION", RegularExpression = @"^427([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,3})$" },
            new ApplicationIdentifier { Ai = "7001", Fnc1Required = true, DataTitle = "NSN", RegularExpression = @"^7001(\d{13})$" },
            new ApplicationIdentifier { Ai = "7002", Fnc1Required = true, DataTitle = "MEAT CUT", RegularExpression = @"^7002([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "7003", Fnc1Required = true, DataTitle = "EXPIRY TIME", RegularExpression = @"^7003(\d{10})$" },
            new ApplicationIdentifier { Ai = "7004", Fnc1Required = true, DataTitle = "ACTIVE POTENCY", RegularExpression = @"^7004(\d{0,4})$" },
            new ApplicationIdentifier { Ai = "7005", Fnc1Required = true, DataTitle = "CATCH AREA", RegularExpression = @"^7005([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,12})$" },
            new ApplicationIdentifier { Ai = "7006", Fnc1Required = true, DataTitle = "FIRST FREEZE DATE", RegularExpression = @"^7006(\d{6})$" },
            new ApplicationIdentifier { Ai = "7007", Fnc1Required = true, DataTitle = "HARVEST DATE", RegularExpression = @"^7007(\d{6,12})$" },
            new ApplicationIdentifier { Ai = "7008", Fnc1Required = true, DataTitle = "AQUATIC SPECIES", RegularExpression = @"^7008([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,3})$" },
            new ApplicationIdentifier { Ai = "7009", Fnc1Required = true, DataTitle = "FISHING GEAR TYPE", RegularExpression = @"^7009([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,10})$" },
            new ApplicationIdentifier { Ai = "7010", Fnc1Required = true, DataTitle = "PROD METHOD", RegularExpression = @"^7010([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,2})$" },
            new ApplicationIdentifier { Ai = "7020", Fnc1Required = true, DataTitle = "REFURB LOT", RegularExpression = @"^7020([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "7021", Fnc1Required = true, DataTitle = "FUNC STAT", RegularExpression = @"^7021([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "7022", Fnc1Required = true, DataTitle = "REV STAT", RegularExpression = @"^7022([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "7023", Fnc1Required = true, DataTitle = "GIAI - ASSEMBLY", RegularExpression = @"^7023([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "7030", Fnc1Required = true, DataTitle = "PROCESSOR # 0", RegularExpression = @"^7030(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7031", Fnc1Required = true, DataTitle = "PROCESSOR # 1", RegularExpression = @"^7031(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7032", Fnc1Required = true, DataTitle = "PROCESSOR # 2", RegularExpression = @"^7032(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7033", Fnc1Required = true, DataTitle = "PROCESSOR # 3", RegularExpression = @"^7033(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7034", Fnc1Required = true, DataTitle = "PROCESSOR # 4", RegularExpression = @"^7034(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7035", Fnc1Required = true, DataTitle = "PROCESSOR # 5", RegularExpression = @"^7035(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7036", Fnc1Required = true, DataTitle = "PROCESSOR # 6", RegularExpression = @"^7036(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7037", Fnc1Required = true, DataTitle = "PROCESSOR # 7", RegularExpression = @"^7037(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7038", Fnc1Required = true, DataTitle = "PROCESSOR # 8", RegularExpression = @"^7038(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7039", Fnc1Required = true, DataTitle = "PROCESSOR # 9", RegularExpression = @"^7039(\d{3})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,27})$" },
            new ApplicationIdentifier { Ai = "7040", Fnc1Required = false, DataTitle = "UIC+EXT", RegularExpression = @"7040(\d[\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{3})$" },
            new ApplicationIdentifier { Ai = "710", Fnc1Required = true, DataTitle = "NHRN PZN", RegularExpression = @"^710([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "711", Fnc1Required = true, DataTitle = "NHRN CIP", RegularExpression = @"^711([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "712", Fnc1Required = true, DataTitle = "NHRN CN", RegularExpression = @"^712([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "713", Fnc1Required = true, DataTitle = "NHRN DRN", RegularExpression = @"^713([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "714", Fnc1Required = true, DataTitle = "NHRN AIM", RegularExpression = @"^714([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "7230", Fnc1Required = true, DataTitle = "CERT #1", RegularExpression = @"^7230([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7231", Fnc1Required = true, DataTitle = "CERT #2", RegularExpression = @"^7231([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7232", Fnc1Required = true, DataTitle = "CERT #3", RegularExpression = @"^7232([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7233", Fnc1Required = true, DataTitle = "CERT #4", RegularExpression = @"^7233([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7234", Fnc1Required = true, DataTitle = "CERT #5", RegularExpression = @"^7234([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7235", Fnc1Required = true, DataTitle = "CERT #6", RegularExpression = @"^7235([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7236", Fnc1Required = true, DataTitle = "CERT #7", RegularExpression = @"^7236([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7237", Fnc1Required = true, DataTitle = "CERT #8", RegularExpression = @"^7237([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7238", Fnc1Required = true, DataTitle = "CERT #9", RegularExpression = @"^7238([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7239", Fnc1Required = true, DataTitle = "CERT #10", RegularExpression = @"^7239([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{2,30})$" },
            new ApplicationIdentifier { Ai = "7240", Fnc1Required = false, DataTitle = "PROTOCOL", RegularExpression = @"7240 ([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "8001", Fnc1Required = true, DataTitle = "DIMENSIONS", RegularExpression = @"^8001(\d{14})$" },
            new ApplicationIdentifier { Ai = "8002", Fnc1Required = true, DataTitle = "CMT No", RegularExpression = @"^8002([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "8003", Fnc1Required = true, DataTitle = "GRAI", RegularExpression = @"^8003(\d{14})([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,16})$" },
            new ApplicationIdentifier { Ai = "8004", Fnc1Required = true, DataTitle = "GIAI", RegularExpression = @"^8004([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "8005", Fnc1Required = true, DataTitle = "PRICE PER UNIT", RegularExpression = @"^8005(\d{6})$" },
            new ApplicationIdentifier { Ai = "8006", Fnc1Required = true, DataTitle = "ITIP", RegularExpression = @"^8006(\d{14})(\d{2})(\d{2})$" },
            new ApplicationIdentifier { Ai = "8007", Fnc1Required = true, DataTitle = "IBAN", RegularExpression = @"^8007([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,34})$" },
            new ApplicationIdentifier { Ai = "8008", Fnc1Required = true, DataTitle = "PROD TIME", RegularExpression = @"^8008(\d{8})(\d{0,4})$" },
            new ApplicationIdentifier { Ai = "8009", Fnc1Required = true, DataTitle = "OPTSEN", RegularExpression = @"^8009([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,50})$" },
            new ApplicationIdentifier { Ai = "8010", Fnc1Required = true, DataTitle = "CPID", RegularExpression = @"^8010([\x23\x2D\x2F\x30-\x39\x41-\x5A]{0,30})$" },
            new ApplicationIdentifier { Ai = "8011", Fnc1Required = true, DataTitle = "CPID SERIAL", RegularExpression = @"^8011(\d{0,12})$" },
            new ApplicationIdentifier { Ai = "8012", Fnc1Required = true, DataTitle = "VERSION", RegularExpression = @"^8012([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,20})$" },
            new ApplicationIdentifier { Ai = "8013", Fnc1Required = true, DataTitle = "GMN (for medical devices, the default, global data title is BUDI-DI)", RegularExpression = @"^8013([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "8017", Fnc1Required = true, DataTitle = "GSRN - PROVIDER", RegularExpression = @"^8017(\d{18})$" },
            new ApplicationIdentifier { Ai = "8018", Fnc1Required = true, DataTitle = "GSRN - RECIPIENT", RegularExpression = @"^8018(\d{18})$" },
            new ApplicationIdentifier { Ai = "8019", Fnc1Required = true, DataTitle = "SRIN", RegularExpression = @"^8019(\d{0,10})$" },
            new ApplicationIdentifier { Ai = "8020", Fnc1Required = true, DataTitle = "REF No", RegularExpression = @"^8020([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,25})$" },
            new ApplicationIdentifier { Ai = "8026", Fnc1Required = true, DataTitle = "ITIP CONTENT", RegularExpression = @"^8026(\d{14})(\d{2})(\d{2})$" },
            new ApplicationIdentifier { Ai = "8110", Fnc1Required = true, DataTitle = "", RegularExpression = @"^8110([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,70})$" },
            new ApplicationIdentifier { Ai = "8111", Fnc1Required = true, DataTitle = "POINTS", RegularExpression = @"^8111(\d{4})$" },
            new ApplicationIdentifier { Ai = "8112", Fnc1Required = true, DataTitle = "", RegularExpression = @"^8112([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,70})$" },
            new ApplicationIdentifier { Ai = "8200", Fnc1Required = true, DataTitle = "PRODUCT URL", RegularExpression = @"^8200([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,70})$" },
            new ApplicationIdentifier { Ai = "90", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^90([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,30})$" },
            new ApplicationIdentifier { Ai = "91", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^91([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "92", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^92([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "93", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^93([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "94", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^94([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "95", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^95([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "96", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^96([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "97", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^97([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "98", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^98([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
            new ApplicationIdentifier { Ai = "99", Fnc1Required = true, DataTitle = "INTERNAL", RegularExpression = @"^99([\x21-\x22\x25-\x2F\x30-\x39\x41-\x5A\x5F\x61-\x7A]{0,90})$" },
        };

        private sealed class ApplicationIdentifier
        {
            public string Ai { get; set; }

            public string DataTitle { get; set; }

            public bool Fnc1Required { get; set; }

            public string RegularExpression { get; set; }
        }
    }
}
